name: tubes
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  camera: ^0.11.0
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.1
  speech_to_text: ^7.0.0
  fluttertoast: ^8.0.9
  rflutter_alert: ^2.0.3
  awesome_snackbar_content: ^0.1.1

  image_picker: ^0.8.7+4

  pdf: ^3.10.5
  path_provider: ^2.0.11
  permission_handler: ^10.3.2
  barcode_widget: ^2.0.1
  http: ^1.2.2
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/img_poster/
    - images/img_fnb/

  fonts:
    - family: "Poppins-Bold"
      fonts:
        - asset: fonts/Poppins-Bold.ttf

    - family: "Poppins-SemiBold"
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf

    - family: "Poppins-Medium"
      fonts:
        - asset: fonts/Poppins-Medium.ttf

    - family: "Poppins-Regular"
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: "Poppins-Light"
      fonts:
        - asset: fonts/Poppins-Light.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
